final Map<String, String> listcourseValues = {
  'Tous': 'Tous',
  'F62_03': 'Action civile',
  'F62_02': 'Action publique',
  'F23_08': 'Aggressions sexuelles',
  'F62_44': 'Auditions et confrontations',
  'F62_40': 'Cadres généraux d\'enquête',
  'F62_41': 'Cadres particuliers d\'enquête',
  'F61_15': 'Circonstances aggravantes',
  'F62_38': 'Criminalité et délinquance organisées',
  'F23_41': 'Destructions, dégradations et détériorations',
  'F61_08': 'Définition et classification des peines',
  'F62_32': 'Enfance délinquante',
  'F23_34': 'Escroquerie',
  'F23_00': 'Étude du droit pénal spécial',
  'F23_33': 'Extorsion et chantage',
  'F62_43': 'Garde à vue',
  'F62_42': 'Information au PR, transport, constatations et réquisitions',
  'F23_35': 'Infractions voisines de l\'escroquerie',
  'F61_02': 'L\'infraction',
  'F61_03': 'La classification des infractions',
  'F61_07': 'La complicité',
  'F62_01': 'La faute civile et la faute pénale',
  'F61_04': 'La tentative punissable',
  'F62_04': 'Le ministère public',
  'F62_10': 'Les APJ et les APJA',
  'F62_16': 'Les juridictions d\'instruction',
  'F62_09': 'Officiers de police judiciaire',
  'F62_45': 'Perquisitions et saisies',
  'F62_08': 'Police judiciaire',
  'F62_24': 'Preuve en matière répressive',
  'F61_01': 'Présentation du droit pénal',
  'F23_40': 'Recel et infractions voisines',
  'F23_60': 'Usurpation ou usage irrégulier de fonctions, nom ou qualité',
  'F23_32': 'Vol'
};
final listmonthValues = <String>['Tous', 'Juillet / Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];
